In [ ]:
!pip list

In [1]:
import torch

In [2]:
torch.cuda.is_available()

False

**Tensors**
<br>
Tensors are multidimensional arrays like numpy arrays but the difference is that they are computed faster by GPU's and are differentiated using autograd useful for training of NN


In [3]:
#Empty Tensors
x = torch.empty(3)
print(f'''Empty Tensor : {x}''')

#Random Tensors
y = torch.rand(2)
print(f'''Random Tensor : {y}''')

#Zeros Tensor
z = torch.zeros(2)
print(f'''Zeros Tensor : {z}''')

#Ones Tensor
a = torch.ones(3, dtype=torch.int)
print(f'''Ones Tensor : {a}''')

#Tensor From a List
b = torch.tensor([1,2,3])
print(f'''Tensor From List : {b}''')

Empty Tensor : tensor([2.7415e-24, 4.4654e-41, 2.7415e-24])
Random Tensor : tensor([0.4774, 0.0901])
Zeros Tensor : tensor([0., 0.])
Ones Tensor : tensor([1, 1, 1], dtype=torch.int32)
Tensor From List : tensor([1, 2, 3])


In [4]:
t1 = torch.rand(2,2)
t2 = torch.rand(2,2)
print(t1)
print(t2)
t3 = t1 + t2
# we could also do z = torch.add(t1,t2)
#also could do y.add_(x) this will add x in y and store the value in y
#print(t3)
# t2.add_(t1)
# print(t2)
print(t3)

# Note :- every function with a underscore after it will apply the operation and store it dirctly in the variable on which it is applied

tensor([[0.0484, 0.8230],
        [0.3232, 0.3268]])
tensor([[0.7515, 0.1402],
        [0.2458, 0.5469]])
tensor([[0.8000, 0.9633],
        [0.5689, 0.8736]])


In [5]:
t3 = torch.rand(2,2)
t4 = torch.rand(2,2)
t5 = t3 - t4
# or t5 = torch.sub(t3,t4)
# or t4.sub_(t3)
print(t5)

tensor([[ 0.2648, -0.0565],
        [-0.1904, -0.4577]])


In [6]:
# Similarly we have operations like
# torch.mul()
# torch.div()

In [7]:
# Slicing Operation
t6 = torch.rand(3,3)
print(t6)
# First Column only
print(t6[:,0])
# First Row Only
print(t6[0,:])
# Particular Element
print(t6[0,0].item()) #.item gets actual value of 1X1 tensor

tensor([[0.0638, 0.6455, 0.4517],
        [0.4690, 0.6155, 0.9954],
        [0.0821, 0.4384, 0.5159]])
tensor([0.0638, 0.4690, 0.0821])
tensor([0.0638, 0.6455, 0.4517])
0.06378120183944702


In [8]:
# Reshaping Tensor
t7 = torch.rand(4,4)
print(t7)
print(t7.size())
t8 = t7.view(16)
print(t8.size())
t9 = t7.view(-1,2)
print(t9.size())

tensor([[0.9463, 0.9801, 0.2549, 0.5745],
        [0.9351, 0.0377, 0.2521, 0.6707],
        [0.6670, 0.7754, 0.6814, 0.8879],
        [0.4332, 0.6041, 0.7275, 0.8165]])
torch.Size([4, 4])
torch.Size([16])
torch.Size([8, 2])


In [9]:
# Converting From a Numpy to a Tensor
import numpy as np

t10 = torch.ones(5)
print(t10)
numpy_t10 = t10.numpy()
print(numpy_t10)
print(type(numpy_t10))

# If tensor is on CPU than GPU then both will share same memory location and
# if one changes other will change as well

# This memory-sharing behavior only happens when the tensor is on the CPU.
# If the tensor is on a GPU (CUDA tensor), the .numpy() method
# will raise an error since NumPy cannot directly work with GPU memory.
# In that case, you would need to move the tensor to the CPU first (using .cpu())
# before converting it to a NumPy array.

tensor([1., 1., 1., 1., 1.])
[1. 1. 1. 1. 1.]
<class 'numpy.ndarray'>


In [10]:
# Converting a numpy array to tensor
numpy_t11 = np.ones(5)
print(numpy_t11)
t11 = torch.from_numpy(numpy_t11)
print(t11)
# t11 = t11.type(torch.int32)
# print(t11)
# print(t11.dtype)

[1. 1. 1. 1. 1.]
tensor([1., 1., 1., 1., 1.], dtype=torch.float64)


In [11]:
t12 = torch.ones(3)
t12 += 1 # inplace tensor change which is allowed
print(t12)
t12 + 1 #Created a new tensor and did not change original
print(t12)

tensor([2., 2., 2.])
tensor([2., 2., 2.])


In [13]:
if torch.cuda.is_available():
  device = torch.device('cuda') #Changes the device to be used to cuda
  x = torch.ones(3,device = device) #Creates a tensor on the GPU
  y = torch.one(3) #Create a tensor on GPU
  y = y.to(device) #Brought that tensor on GPU
  z = x + y
  # z.numpy() This will not work because cannot convert GPU tensor to num
  # z = z.to('cpu') first move it to the cpu then it will work

In [ ]:
t16 = torch.one(3,requires_grad=True) #requires_grad tells that we need to perform gradient descents and optimize this tensor